export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const FETCH_BARTERS_REQUEST = "FETCH_BARTERS_REQUEST";
export const FETCH_BARTERS_SUCCESS = "FETCH_BARTERS_SUCCESS";
export const FETCH_BARTERS_FAILURE = "FETCH_BARTERS_FAILURE";

export const CREATE_BARTER_REQUEST = "CREATE_BARTER_REQUEST";
export const CREATE_BARTER_SUCCESS = "CREATE_BARTER_SUCCESS";
export const CREATE_BARTER_FAILURE = "CREATE_BARTER_FAILURE";

export const UPDATE_BARTER_REQUEST = "UPDATE_BARTER_REQUEST";
export const UPDATE_BARTER_SUCCESS = "UPDATE_BARTER_SUCCESS";
export const UPDATE_BARTER_FAILURE = "UPDATE_BARTER_FAILURE";

export const DELETE_BARTER_REQUEST = "DELETE_BARTER_REQUEST";
export const DELETE_BARTER_SUCCESS = "DELETE_BARTER_SUCCESS";
export const DELETE_BARTER_FAILURE = "DELETE_BARTER_FAILURE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
